# Generated by Django 4.1.3 on 2022-12-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fklike.net%2F2561-kartinki-gitary-40-foto.html&psig=AOvVaw0DxKcXk2HoJTeigOjGAnNq&ust=1670516625324000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCNjuqsL15_sCFQAAAAAdAAAAABAE'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(default='Post', max_length=230),
        ),
    ]
