# Generated by Django 4.1.3 on 2022-12-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
